// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjnelbzvsqexwiwcwxcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbmVsYnp2c3FleHdpd2N3eGNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDM2NDAsImV4cCI6MjA2MjcxOTY0MH0.NIayokiB9PbDNvc6dX7CdHtfX3SM4pXlYiFyNiIukPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);