// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzrhugkzszjngtqxsyzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6cmh1Z2t6c3pqbmd0cXhzeXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzg2MzUsImV4cCI6MjA2MjYxNDYzNX0.qr-Wic6sf-sTtnYKkxvTWvxzJTRV5a_T-bElvs50uUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);